name: Publish master docker image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    environment: master
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Resolve docker image name
        id: image_name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.image_name.outputs.IMAGE_NAME }}
 
      - name: Download Keycloak Last Login Event Listener
        env:
          LAST_LOGIN_EVENT_LISTENER_EXTENSION_VERSION: 0.0.2
        id: download_last_login_event_listener
        run: |
          echo "Downloading Keycloak Last Login Event Listener version ${{ env.LAST_LOGIN_EVENT_LISTENER_EXTENSION_VERSION }}" &&
          mkdir -p providers &&
          curl --fail -L "https://github.com/slemke/keycloak-last-login-event-listener/releases/download/v${{ env.LAST_LOGIN_EVENT_LISTENER_EXTENSION_VERSION }}/keycloak-last-login-event-listener.jar" -o providers/last-login-event-listener.jar
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ steps.image_name.outputs.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}